# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Needed for backward compatibility
gems: [jekyll-paginate]

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Guillaume Lauzier'
tagline:          'Developer & Entrepreneur'
description:      'Guillaume Lauzier is a entrepreneur, full stack web iOS and blockchain developer.'
url:              'http://www.guillaumelauzier.com'
baseurl:          'PersonalSite'

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/


# Author Details
author:         'Guillaume Lauzier'

#Social Media links (Use complete URL except for email)
dribbble:
email:          'mailto:guillaumelauzier@gmail.com
facebook:       
flickr:
github:         'https://github.com/guillaumelauzier'
gplus:          
instagram:
pinterest:
linkedin:       'https://linkedin.com/in/guillaumelauzier'
rss:
stackoverflow: 
twitter:        'https://twitter.com/olakara'

# Google Analytics
gahandler: 'UA-35910281-42'

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'testingblogo'

# txtpen
txtpenhandler: 'testingblogo'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2
